###
# curl -H "Content-Type: application/json"      -X POST http://localhost:8081/api/ask      -d '{"question":"How should I adjust my heating?"}'
POST http://localhost:8081/api/ask
Content-Type: application/json

{
  "question": "How should I adjust my heating?"
}

###
# curl -H "Content-Type: application/json"      -X POST http://localhost:8081/api/ask      -d '{"question":"Should I open the windows? I'm feeling a bit dizzy! Do I need a doctor?"}'
POST http://localhost:8081/api/ask
Content-Type: application/json

{
  "question": "Should I open the windows? I'm feeling a bit dizzy! Do I need a doctor?"
}

