spring:
  application:
    name: mcp-client-ha
  ai:
    mcp:
      client:
        sse:
          connections:
            ha:
              url: http://localhost:8080

server:
  port: 8081

logging:
  level:
    io.modelcontextprotocol.spec.McpClientSession: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG

---
spring:
  config:
    activate:
      on-profile: ollama-local
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:3b
          temperature: 0.7
          top-p: 0.9
          num-predict: 2048
---
spring:
  config:
    activate:
      on-profile: ollama-cloud
  ai:
    openai:
      api-key: ${OLLAMA_API_KEY}
      base-url: https://ollama.com/
      chat:
        options:
          model: gpt-oss:20b-cloud
          temperature: 1.5          # Maximal hochsetzen für maximale Entropie
          top-p: 1.0                # Keine Filterung durch Nucleus Sampling
          max-tokens: 2048         # OpenAI nutzt max-tokens statt num-predict    mcp:
      client:
        sse:
          connections:
            ha:
              url: http://localhost:8080
server:
  port: 8081

logging:
  level:
    io.modelcontextprotocol.spec.McpClientSession: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG

